### PR TITLE
allowing for specifying multiple service body IDs

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by radius314** [comment]
@pjaudiomv

**Comment by LittleGreenViper** [comment]
Approved. Same deal as usual, but this is currently planned for the next release of the root, as it’s fairly minor.

That said, if we need it sooner, I can do a release, but I like to avoid a bunch of small releases.

**Comment by pjaudiomv** [comment]
Sweet! Thanks guys!

**Comment by LittleGreenViper** [comment]
Just FYI: I also updated the version and README for the next release. I always like to keep a running log in the changelog part of the README (Which, if you look at it, goes back nine years).

**Comment by pjaudiomv** [comment]
Thanks. I don't need this in an official release till whenever your ready for next release. I'm just gonna pull the master and put it on my test server for now to play with it. Thanks Danny and Chris

**Comment by pjaudiomv** [comment]
Chris, I read through that whole log one day to get a better understanding of evolution of BMLT 😂

**Comment by LittleGreenViper** [comment]
Quite a saga, eh?

**Comment by radius314** [comment]
Non urgent

**Pull request merged**
