### PR TITLE
jsonp endpoint

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by radius314** [comment]
@jbraswell is this implemented in tomato?

**Comment by LittleGreenViper** [comment]
I merged it in, as I feel it's safe enough. It doesn't touch any of the existing code. However, we should give it good testing, and add it to the documentation.

**Comment by radius314** [comment]
ACK

**Comment by radius314** [comment]
LGTM https://codepen.io/radius314/pen/RMxQrB

**Comment by LittleGreenViper** [comment]
Sweet!
I have also sent the code to the test server: https://tkddevel.com/bmltwork/bmlt/main_server/

**Comment by jbraswell** [comment]
@radius314 jsonp is unsupported in tomato

**Comment by LittleGreenViper** [comment]
I've never been that thrilled with JSONP. It seems a bit of a hack. However, I'm happy to support it in this fashion.
We should remember that whatever we add, we add forever. We'll be responsible for supporting it until The End Times.
Microsoft is even known for PUTTING BUGS BACK in their software, as developers had coded their apps to compensate for the issues, and the fixes broke apps.

**Comment by radius314** [comment]
Yeah it’s not ideal.  But it’s a lot easier than explaining CORS headers.
It’s a simple feature to support forever.

**Pull request merged**
