### PR TITLE
*DO NOT MERGE* auto save geocode

### PR DESCRIPTION
**Pull request by radius314**
**DO NOT MERGE**

This pull request needs some discussion, it's definitely not ready to be merged. 

In working this issue a couple of things comes to mind.  

1) Not everyone will want to do this.
2) People will want granular control.
3) This will not help mobile apps, so perhaps this should be serverside.

Looking for commentary, feedback before I spend any more time on this.

@jbraswell @pjaudiomv @LittleGreenViper

### CODE REVIEW

**Comment by pjaudiomv** [comment]
cool!
for numbers
1. yes this should be option
2. yes granular control is key as even if location is entered correct google doesnt always geocode things properly.
3. i think server side would be best way to go as well

**Comment by LittleGreenViper** [comment]
Oh...yeah, one other thing. Patrick is right. This should be done server-side, in PHP.

**Comment by radius314** [comment]
Ok, the server side part is definitely what I was thinking, in order to properly encapsulate the feature.

It seems as the default function should be to always do the lookup, and then provide the ability to handle the exception cases mentioned in 1 + 2 of your comment @LittleGreenViper.

I can't think of an easy to create this way to override the proposed auto-save feature.

**Comment by LittleGreenViper** [comment]
It's a great idea, but nuking people's custom settings will cause insane rage from insane ragers.

This was something that I gave a lot of thought to as I set things up. I had to hode by dose (hold my nose) when I did things the way I did. I hate to compromise user experience; especially when it increases the chance for error.

**Comment by radius314** [comment]
I know what you mean and I'm cautious of that as well...

Maybe the approach should be an option in your config file to turn this on.  It's not the default experience so people can opt-in or choose to keep this feature status quo.

**Comment by radius314** [comment]
The one part that would be missing would be a way to allow individual overrides.  Someone will want the best of both worlds... I can think of a way to hack it.  Perhaps 

When you say the installer needs work, do you have more detail about what work?

**Comment by LittleGreenViper** [comment]
I think that I have added one or two fields (can't remember what, exactly) that aren't reflected in the GUI. These are usually checkboxes.

It's a big fat pain to tweak the GUI. It's not the cleanest JS on Earth. I kinda hacked it out over a weekend, because I was getting a lot of complaints about setting up the config file.

As far as documenting the file, it would probably be enough to just add some good comments into a template file, like what I do with the BMLT-Basic config file.

**Pull request closed without merging**
